[package]
name = "example"
type = "bin"
authors = [""]
compiler_version = ">=1.0.0"

[dependencies]
rsa = { path = "../lib" }
bignum = { tag = "v0.5.0", git = "https://github.com/noir-lang/noir-bignum" }
