[package]
name = "example"
type = "bin"
authors = [""]
compiler_version = ">=0.35.0"

[dependencies]
rsa = { path = "../lib" }
bignum = { tag = "v0.4.0", git = "https://github.com/noir-lang/noir-bignum" }
